name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  insure_tech:
    +materialized: view  # Default for everything, unless overridden
    +on_schema_change: sync_all_columns  # Optional, but good for incremental
    # You can override materialization by folder
    01_stg:
      +materialized: view
    02_int:
      +materialized: incremental
      +incremental_strategy: merge
    03_fct:
      +materialized: incremental
      +incremental_strategy: merge
    03_dim:
      +materialized: incremental
      +incremental_strategy: merge
    04_marts:
      +materialized: incremental
      +incremental_strategy: merge

